enum class ConnectFourGameMode {
    SINGLE_PLAYER_VS_RANDOM_AI,
    SINGLE_PLAYER_VS_COMPUTER_AI,
    TWO_PLAYER,
    SINGLE_PLAYER_VS_COMPUTER_AI_2,
    COMPUTER_AI_2_VS_COMPUTER_AI_2,
    COMPUTER_AI_VS_COMPUTER_AI,
}
